
port: 8000

mappings:
  - type: tcp
    from: ":8080"
    to: "localhost:80"
  - type: tcp
    from: ":8443"
    to: "localhost:443"
  - type: tcp
    from: ":2222"
    to: "localhost:22"
  - type: udp
    from: ":5333"
    to: "8.8.8.8:53"